spring:
  application:
    name: cbyk-api
  datasource:
    url: jdbc:postgresql://db:5432/dbcbyk?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: GMT-3

springdoc:
  packagesToScan: com.cbyk

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
